### ISSUE TITLE
feature request for hue/deconz

### ISSUE THREAD

**Issue by holli73** [plan44/vdcd#2]
hello Lukas,

i don't know the osram/hue gateways but i'm sure that you can make groups of lights and turn them on/off at once and store scences for those groups as i can do in deconz.

so it would be cool if the vdcd could provide this groups as devices and they can have the same options as the single light and maybe a combo box with the available scenes for this group.

why?

f. ex. in my living room i have apx. 12 spots and if i use the vdcd to turn them on it is like on an airport you can see each light coming on - if if do the same through the group of deconz all light go on at the same time - this looks much better than every second a light turns on - that means till my living room is complete on it takes some seconds if i call the group it is on...

i hope this makes sense - i believe even the philips/osram should have this function build in because in most cases you will have more than one light in a room and want to turn them on/off instantly.

what do you think?

best regards
holli

**Comment by plan44** [comment]
Hello holli,

> On 16.05.2015, at 19:57, holli73 notifications@github.com wrote:
> 
> i don't know the osram/hue gateways but i'm sure that you can make groups of lights and turn them on/off at once and store scences for those groups as i can do in deconz.
> 
> so it would be cool if the vdcd could provide this groups as devices and they can have the same options as the single light and maybe a combo box with the available scenes for this group.

These group devices would overlap the individual devices and this would be confusing and inconsistent from a digitalSTROM point of view. Even more so if digitalSTROM scenes and ZLL scenes would get mixed - the concepts of rooms and scenes in digitalSTROM are simply too different from ZLL.

> f. ex. in my living room i have apx. 12 spots and if i use the vdcd to turn them on it is like on an airport you can see each light coming on - if if do the same through the group of deconz all light go on at the same time - this looks much better than every second a light turns on - that means till my living room is complete on it takes some seconds if i call the group it is on...

Is it really that slow? I have a bunch of hues in the same room, but don't notice any visible delay.

If you see delays between lamps in the seconds, there must be a performance problem somewhere. In the P44-DSB-DEH, the vdcd runs on a really small and slow platform, even when compared with a Raspberry Pi, let alone a real PC or Mac. Still, it is fast enough even then to send hue API requests quickly enough so multiple hue lights appear to change simultaneously. Maybe deconz is much slower than the hue bridge?

> i hope this makes sense - i believe even the philips/osram should have this function build in because in most cases you will have more than one light in a room and turn them on.

It makes sense to provide grouping and scenes for pure ZLL systems, but I doubt these features are there because of speed limitations of the technology.

Lukas

**Comment by holli73** [comment]
hello Lukas,

so i'm getting close to finish my installation now i have up to 70 osram devices on the DECONZ and it works but not as expected with the vdsm

if i use the deconz webapi to control the lights it is on/off immideatly as mentioned but not through digitalstrom - further i have a room (bath) with 19 zigbee spots f. ex. my living room has 11 spots and there all lights come on but as mentioned like on a runway of an airport - but now my bath is finished i do not get all lights on max. 14 lights will come on through vdsm - is there any debug i can do to find out why it is so slow and why are not all lights coming on - i also tried to run the vdsm on the same pi as deconz - but this makes no difference at all - both pi are on the same switch...

any idea how i can figure out what the problem is with the delays and not all lights coming on?

thanks
holli

**Comment by plan44** [comment]
Hello Holli,

> On 14.08.2015, at 08:25, holli73 notifications@github.com wrote:
> 
> hello Lukas,
> 
> so i'm getting close to finish my installation now i have up to 70 osram devices on the DECONZ and it works but not as expected with the vdsm

it's the vdcd which actually communicates with the hue bridge (or, in your case, with DECONZ). The vdsm is only the intermediate between vdcd and dSS.

> if i use the deconz webapi to control the lights it is on/off immideatly as mentioned but not through digitalstrom - further i have a room (bath) with 19 zigbee spots f. ex. my living room has 11 spots and there all lights come on but as mentioned like on a runway of an airport - but now my bath is finished i do not get all lights on max. 14 lights will come on through vdsm - is there any debug i can do to find out why it is so slow and why are not all lights coming on - i also tried to run the vdsm on the same pi as deconz - but this makes no difference at all - both pi are on the same switch...

I have no experience with DECONZ, but the original hue bridge's API is not extremely speedy. When you have 19 zigbee spots, this means 19 requests to the bridge to turn them on or off, so even relatively small delays in processing them could cause the airport runway effect.

In addition, to conform to digitalSTROM light behaviour, when calling a scene the vdcd needs to query each light's current state before sending the new state. This might also be a reason for slowing down the operation - it very much depends on how much of the light's state DECONZ has in cache or needs to query over zigbee from the light itself every time.

> any idea how i can figure out what the problem is with the delays and not all lights coming on?

You can switch the vdcd to a higher log level (normal is 5, if you set it to 6 or 7 you will see the JSON communication between vdcd and DECONZ with timestamps, so it should be possible to figure out where the delays originate from.

Lukas

BTW: there's now a vdcd mailing list: http://groups.google.com/group/plan44_vdcd / plan44_vdcd@googlegroups.com that might be better suited for vdcd related questions and discussions.

**Comment by holli73** [comment]
hello Lukas,

so i will post the log in the mailing list?
and we should close this ticket?

in the meantime i created a small script which can call on/off and defined scenes direkt as a single web call from digitalstrom - with this web call i get all lights always on and instantly 

so i still believe the best way to work with deconz/hue/lightify would be to have a group as device and and than assign this group to a room and i could name the scene (stimmung 1/...) and which i believe simple effort this should work best - because then all is stored on the zigbee servers and vdcd just need a single or 2 calls to get the state (not sure if even needed) and than call the scene or ON/OFF.

please let me know if i should post the log into the mailing list or here.

thanks
holli

PS: i bought a lightify gw to update the fw of my devices but the interface looks close to deconz as well room = group and you can define szenes there...

**Comment by plan44** [comment]
Hello Holli,

I think the mailing list is better, because the discussion might be of general interest for other vdcd users.

Best Regards,

Lukas
