### ISSUE TITLE
Password requested on "git submodule update" on vdcd building process

### ISSUE THREAD

**Issue by KarlKiel** [plan44/vdcd#8]
Hi, I am trying to install vdcd to a RasPi following the guide - nevertheless, during the fetching of the p44vdc and p44utils submoduls ("git submodule update") it is asking for plan44's password on plan44.ch "plan44@plan44's password:" - Where do I get this to update the submodules successfully?
Thanks in advance for your support.
BR,
Arne

**Comment by KarlKiel** [comment]
Ok, I edited the .gitmodules to pull from open p44 git repository and was able to build. Nevertheless - maybe this should be fixed to point to the openly available repository...

**Comment by plan44** [comment]
You are right, the paths in .gitmodule must be relative and should not contain references to my non-public working repos. This was already the case for p44vdc and p44utils, but I oversaw that for the recently added p44lrgraphics. It is fixed now. Thanks for reporting the problem!
